garlic_bread_ingredients = [
    {
        'ingredient_name': 'garlic salt',
        'ingredient_amount': 2,
        'ingredient_units': 'tsp',
        'optional': False,
        'prep': '',
    },
    {
        'ingredient_name': 'bread',
        'ingredient_amount': 6,
        'ingredient_units': 'slices',
        'optional': False,
        'prep': '',
    },
    {
        'ingredient_name': 'butter',
        'ingredient_amount': 1,
        'ingredient_units': 'Tbsp',
        'optional': False,
        'prep': '',
    },
]

black_bean_enchiladas_ingredients = [
    {
        'ingredient_name': 'enchilada sauce',
        'ingredient_amount': 2,
        'ingredient_units': 'cups',
        'optional': False,
        'prep': '',
    },
    {
        'ingredient_name': 'olive oil',
        'ingredient_amount': 2,
        'ingredient_units': 'Tbsp',
        'optional': False,
        'prep': '',
    },
    {
        'ingredient_name': 'red onion',
        'ingredient_amount': 1,
        'ingredient_units': 'cup',
        'optional': False,
        'prep': 'chopped',
    },
    {
        'ingredient_name': 'red bell pepper',
        'ingredient_amount': 1,
        'ingredient_units': 'whole',
        'optional': False,
        'prep': 'chopped',
    },
    {
        'ingredient_name': 'broccoli',
        'ingredient_amount': 1,
        'ingredient_units': 'bunch',
        'optional': False,
        'prep': 'florets removed and sliced',
    },
    {
        'ingredient_name': 'cumin',
        'ingredient_amount': 1,
        'ingredient_units': 'tsp',
        'optional': False,
        'prep': '',
    },
    {
        'ingredient_name': 'cinammon',
        'ingredient_amount': 0.25,
        'ingredient_units': 'tsp',
        'optional': False,
        'prep': '',
    },
    {
        'ingredient_name': 'spinach',
        'ingredient_amount': 5,
        'ingredient_units': 'oz',
        'optional': True,
        'prep': 'packed',
    },
    {
        'ingredient_name': 'black beans',
        'ingredient_amount': 15,
        'ingredient_units': 'oz',
        'optional': False,
        'prep': 'drained and rinsed',
    },
    {
        'ingredient_name': 'shredded Monterey Jack cheese',
        'ingredient_amount': 1,
        'ingredient_units': 'cup',
        'optional': False,
        'prep': 'divided',
    },
    {
        'ingredient_name': 'salt',
        'ingredient_amount': 0.5,
        'ingredient_units': 'tsp',
        'optional': False,
        'prep': 'to taste',
    },
    {
        'ingredient_name': 'black pepper',
        'ingredient_amount': '',
        'ingredient_units': '',
        'optional': False,
        'prep': 'to_taste',
    },
    {
        'ingredient_name': 'tortillas',
        'ingredient_amount': 8,
        'ingredient_units': '8-inch',
        'optional': False,
        'prep': '',
    },
    {
        'ingredient_name': 'cilantro',
        'ingredient_amount': 1,
        'ingredient_units': 'handful',
        'optional': False,
        'prep': 'chopped, for garnishing',
    },
]
